### ISSUE TITLE
include promise

### ISSUE THREAD

**Issue by leizard** [pradel/meteor-ionic-push#1]
Hi. I'm trying to use your package but I want to include promise to return callback of response. How can I archive this ?
Thank you.

**Comment by pradel** [comment]
to get the callback you can do:

```
var res = IonicPush.send({
            'tokens': my_users_token,
            'notification': {
                'alert': message
            }
        });
console.log(res);
```

or if you use meteor 1.3 you can use this package https://github.com/pradel/ionic-push
